# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-22 14:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=15)),
                ('port', models.IntegerField()),
                ('host_user', models.CharField(max_length=30)),
                ('host_password', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='LOB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='User_msg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('username', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=60)),
                ('u_h', models.ManyToManyField(to='host_manage.Host')),
            ],
        ),
        migrations.AddField(
            model_name='host',
            name='lob',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='host_manage.LOB'),
        ),
    ]
