# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-23 01:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('host_manage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='lob',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='host_manage.LOB'),
        ),
    ]
